### ISSUE TITLE
core:schema:warn Default value `null` does not match type `string` in component `a-keyboard` 

### ISSUE THREAD

**Issue by polhaghverdian** [WandererOU/aframe-keyboard#14]
Hi,

`<a-entity a-keyboard id="keyboard" scale="4 4 5" position="0 0 -3"></a-entity>`

I get below warning in firefox browser with aframe version 1.0.0

core:schema:warn Default value `null` does not match type `string` in component `a-keyboard`

**Comment by avasconcelos114** [comment]
Hello!

Thank you for reporting this issue, I'll look into it and see what I can do to fix it

**Comment by avasconcelos114** [comment]
The [latest PR I merged](https://github.com/WandererOU/aframe-keyboard/pull/15) should fix this warning, let me know if anything doesn't work out well

**Comment by polhaghverdian** [comment]
Great thanks, it works  :)
